services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: taskflow
      POSTGRES_PASSWORD: taskflow
      POSTGRES_DB: taskflow_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    user: "${MY_UID}:${GID}"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://taskflow:taskflow@db/taskflow_development
      RAILS_ENV: development
      BUNDLE_PATH: /rails/vendor/bundle
  css:
    build: .
    command: bundle exec rails tailwindcss:watch[always]
    working_dir: /rails
    user: "${MY_UID}:${GID}"
    volumes:
      - .:/rails
    depends_on:
      - app
    environment:
      RAILS_ENV: development
      BUNDLE_PATH: /rails/vendor/bundle
volumes:
  postgres_data:
